forum/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^msgboard/', include('msgboard.urls')),
]

msgboard/urls.py
from django.conf.urls import url
from . import views

app_name = 'msgboard'

urlpatterns = [
    # /msgboard/
    url(r'^$', views.index, name='index'),

    # /msgboard/3/
    url(r'^(?P<board_id>[0-9]+)/$', views.topics, name='topics'),

    # /msgboard/3/add_topic
    url(r'^(?P<board_id>[0-9]+)/add_topic/$', views.add_topic, name='add_topic'),

    # /msgboard/3/1
    url(r'^(?P<board_id>[0-9]+)/(?P<topic_id>[0-9]+)/$', views.messages, name='messages'),

    # /msgboard/3/1/add_msg
    url(r'^(?P<board_id>[0-9]+)/(?P<topic_id>[0-9]+)/add_msg/$', views.add_msg, name='add_msg'),
]

msgboard/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User

class Board(models.Model):
    name = models.CharField(max_length=32)
    description = models.CharField(max_length=255)
    icon = models.CharField(max_length=1024)

    def __str__(self):
        return self.name

class Topic(models.Model):
    name = models.CharField(max_length=32)
    user = models.ForeignKey(User)
    dateCreated = models.DateTimeField(default=now, null=True)
    isLocked = models.BooleanField(default=False)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Msg(models.Model):
    user = models.ForeignKey(User)
    text = models.CharField(max_length=2048)
    likes = models.IntegerField(default=0)
    dateCreated = models.DateTimeField(default=now, null=True)
    Topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

msgboard/views.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from .models import Board, Topic, Msg
from django.contrib.auth.models import User

def index(request):
    board_list = Board.objects.all()

    return render(request, 'msgboard/index.html', {
        'board_list': board_list, 
    })

# Not proud of this code
class TopicView(Topic):
    username = ''
class MsgView(Msg):
    username = ''

def topics(request, board_id):
    try:
        board = Board.objects.get(pk=board_id)
        topic_list = Topic.objects.filter(board=board_id)

        # not sure why this works... but it does i guess?
        topic_list_view = []
        i = 0
        for topic in topic_list:
            topic_list_view.append(TopicView(topic_list[i]))
            topic_list_view[i] = topic
            topic_list_view[i].username = topic.user 
            i+=1
        #################################################

    except Board.DoesNotExist:
        raise Http404("Board doesn't exist")
        
    return render(request, 'msgboard/topics.html', {
        'board':board,
        'topic_list': topic_list,
    })

def add_topic(request, board_id):
    current_board = get_object_or_404(Board, pk=board_id)
    try:
        title = request.POST['topic_title']
        msg = request.POST['initial_msg']
    except:
        return render(request, 'msgboard/oops.html')
    else:
        topic = Topic(name=title, board=current_board, user=request.user, isLocked=False)
        topic.save()
        msg = Msg(user=request.user, Topic=topic, text=msg)
        msg.save()

        return redirect('msgboard:topics', board_id)

def messages(request, board_id, topic_id):
    try:
        board = Board.objects.get(pk=board_id)
        topic = Topic.objects.get(pk=topic_id)
        msg_list = Msg.objects.filter(Topic=topic_id)

        # not sure why this works... but it does i guess?
        msg_list_view = []
        i = 0
        for msg in msg_list:
            msg_list_view.append(MsgView(msg_list[i]))
            msg_list_view[i] = msg
            msg_list_view[i].username = msg.user
            i+=1
        #################################################

    except Msg.DoesNotExist:
        return render(request, 'msgboard/oops.html')
        
    return render(request, 'msgboard/messages.html', {
        'board':board,
        'msg_list': msg_list_view,
        'topic': topic,
})

def add_msg(request, board_id, topic_id):
    current_topic = get_object_or_404(Topic, pk=topic_id)
    try:
        reply = request.POST['reply']
    except:
        return render(request, 'msgboard/oops.html')
    else:
        msg = Msg(user=request.user, Topic=current_topic, text=reply)
        msg.save()

        return redirect('msgboard:messages', board_id, topic_id)

msgboard/templates/msgboard/index.html
{% load staticfiles %}

<head>
    <link href="{%  static 'favicon.ico' %}" rel="shortcut icon"/>

    <style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 300px;
        background-color:rgb(185, 245, 255);
    }

    td {
        width: 300px;
    }
    
    td, th {
        border: none;
        text-align: center;
        padding: 8px;
    }
    </style>
</head>

<center><h1>Daniel's Message Board</h1></center>

{% if board_list %}
    {% for board in board_list %}
        <div style="width:300px;margin-right: auto; margin-left: auto;">
            <a href="{% url 'msgboard:topics' board.id %}" style="width:300px; text-decoration:none;">
                <table>
                    <tr>
                        <td><img src="{% static board.icon %}" style="width:64px;height:64px;" /></td>
                    </tr>
                    <tr>
                        <td><h2>{{ board.name }}</h2></td>
                    </tr>
                    <tr>
                        <td>{{board.description}}</td>
                    </tr>
                </table>
            </a>
        </div>
    {% endfor %}
    
{% else %}
    <h2>No boards found.</h2>
{% endif%}

msgboard/templates/msgboard/messages.html
<head>
    <style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }
    
    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }
    </style>
</head>

<h2>{{board}} > {{topic}}</h2>

{% if msg_list %}
<table>
    {% for msg in msg_list %}
        <tr>
            <td style="width:300px"><h3>{{msg.user}}</h3><br>Date posted: {{msg.dateCreated}}<br>Likes: {{msg.likes}}</td>
            <td>{{msg.text}}</td>
        </tr>
    {% endfor %}
</table>
{% else %}
<h3>No messages found.</h3>
{% endif%}

{% if user.is_authenticated %}
<form action="{% url 'msgboard:add_msg' board.id topic.id %}" method="POST">
    {% csrf_token %}
    <hr>
    <h3>Add your reply here.</h3>
    <textarea name="reply" cols="40" rows="11"></textarea>
    <hr>
    <input type="submit" value="Submit" />
</form>
{% endif %}

msgboard/templates/msgboard/oops.html
<h1>There has been an error. Sorry about that.</h1>

msgboard/templates/msgboard/topics.html
<head>
    <style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }
    
    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }
    </style>
</head>

<h2>{{board}}</h2>

{% if topic_list %}
    <table>
        {% for topic in topic_list %}
            {% if topic.isLocked %}                 <!--                              -->
            <tr style="background-color:#dddddd"> <!--    Grey out locked topics    -->
            {% else %}                              <!--                              -->
            <tr>                                    <!--                              -->
            {% endif %}
                <td><a href="{% url 'msgboard:messages' board.id topic.id %}">{{ topic.name }}</a></td> 
                <td>{{topic.username}}</td>
                <td>{{topic.dateCreated}}</td>
                <td>{% if topic.isLocked %}LOCKED{% else %}OPEN{% endif %}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <h3>No topics found.</h3>
{% endif%}

{% if user.is_authenticated %}
    <form action="{% url 'msgboard:add_topic' board.id %}" method="POST">
        {% csrf_token %}
        <hr>
        <h3>Not what you're looking for? Create a new topic below.</h3>
        <table>
            <tr>
                <td><label>Title:</label></td>
                <td><textarea style="resize: none;" name="topic_title" cols="40" rows="1"></textarea></td>
            </tr>
            <tr>
                <td><label>Initial post:</label></td>
                <td><textarea name="initial_msg" cols="40" rows="11"></textarea></td>
            </tr>
        </table>
        <br>
        <input type="submit" value="Submit" />
    </form>
{% endif %}